apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::268836234542:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-VkTPOvnObdYh
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::268836234542:user/dev
      username: dev
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-06T02:30:00Z"
  name: aws-auth
  namespace: kube-system
   uid: 14a4fcab-71e7-40f2-ad24-6f6c5be89c41


## Above command to configure and to connect EKS to IAM
## kubectl get configmap aws-auth -n kube-system -o yaml